### ISSUE TITLE
Can't get "NPM start" or "Node Index.js" to start

### ISSUE THREAD

**Issue by DexLuther** [angeloanan/MPC-DiscordRPC#19]
I've been trying to debug this on my own, but run into errors.

Installed everything as written in the instructions on the main page.

Typing "NPM Start" results in the following error:
```
PS C:\Users\dexlu> npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dexlu\AppData\Local\npm-cache\_logs\2021-02-26T22_24_20_340Z-debug.log
```

Attempting to move the terminal into the MPC-DiscordRPC-master folder and then running "npm start"  results:
```
PS C:\Users\dexlu> cd C:\MPC-DiscordRPC-master
PS C:\MPC-DiscordRPC-master> npm start

> MPC-DiscordRPC@0.3.0 start
> del /F /Q mpc-discordrpc.log && pm2 start pm2.config.js

Could Not Find C:\MPC-DiscordRPC-master\mpc-discordrpc.log
'pm2' is not recognized as an internal or external command,
operable program or batch file.
```

Attempting to run "Node index.js" instead results in this:
```
PS C:\MPC-DiscordRPC-master> node index.js
node:internal/modules/cjs/loader:926
  throw err;
  ^

Error: Cannot find module 'fancy-log'
Require stack:
- C:\MPC-DiscordRPC-master\index.js
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:768:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:995:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:92:18)←[39m
    at Object.<anonymous> (C:\MPC-DiscordRPC-master\index.js:1:13)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1091:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:971:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:812:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\MPC-DiscordRPC-master\\index.js'←[39m ]
}
```

**Comment by DexLuther** [comment]
Although probably not relevant here are the contents of the above mentioned log file:
```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\ProgramData\\npmglobal\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'start'
0 verbose cli ]
1 info using npm@7.6.0
2 info using node@v15.10.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\ProgramData\npmglobal\node_modules\npm\npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:project Completed in 0ms
9 timing config:load:file:C:\Users\dexlu\.npmrc Completed in 0ms
10 timing config:load:user Completed in 0ms
11 timing config:load:file:C:\ProgramData\npmglobal\etc\npmrc Completed in 0ms
12 timing config:load:global Completed in 1ms
13 timing config:load:cafile Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:setUserAgent Completed in 1ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 7ms
18 verbose npm-session c5907cee2d628a52
19 timing npm:load Completed in 15ms
20 timing command:run-script Completed in 1ms
21 timing command:start Completed in 5ms
22 verbose stack Error: missing script: start
22 verbose stack     at doRun (C:\ProgramData\npmglobal\node_modules\npm\lib\run-script.js:52:11)
23 verbose cwd C:\Users\dexlu
24 verbose Windows_NT 10.0.19042
25 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\npmglobal\\node_modules\\npm\\bin\\npm-cli.js" "start"
26 verbose node v15.10.0
27 verbose npm  v7.6.0
28 error missing script: start
29 verbose exit 1
```

**Comment by DexLuther** [comment]
Found the problem I was having.

Ran "npm i" again after having moved into the MPC-DiscordRPC-master folder using CD, it installed a "node_modules" folder and everything runs correctly now.
